spring:
  data:
    mongodb:
      host: 192.168.4.11
      port: 19130
      database: china_aeronautical
  jersey:
    application-path: /china-aeronautical/api
  application:
    name: china-aeronautical
  profiles:
    active: local

server:
  port: 9990

jersey:
  swagger:
    port: ${server.port}
    ip: 192.168.1.72
filter:
  cross: true