spring:
  data:
    mongodb:
      uri: mongodb://192.168.1.156:27017/china_aeronautical
  jersey:
    application-path: /china-aeronautical/api
  application:
    name: china-aeronautical

server:
  port: 9991

jersey:
  swagger:
    port: ${server.port}
    ip: 192.168.1.89