spring:
  data:
    mongodb:
      uri: mongodb://192.168.4.11:19130/china_aeronautical
  jersey:
    application-path: /china-aeronautical/api
  application:
    name: china-aeronautical
  profiles:
    active: local

server:
  port: 9990

jersey:
  swagger:
    port: ${server.port}
    ip: 192.168.1.72